version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes: 
      - ./data/db:/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: static
    container_name: db
  app:
    build: .
    container_name: transfer
    ports:
      - "3000:3000"
    volumes:
      - .:/user/src/app
    environment: 
      PORT: 3000
      NODE_ENV: production
      DATABASE: static
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE_HOST: db
      DIALECT: postgres
      UPLOAD_DIR: /public/files/
    depends_on: 
      - db
    links: 
      - db
    command: ["node", "./dist/index.js"]
